#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

PROG=/opt/frp/frpc
RES_DIR=/opt/frp/
CONF_DIR=/opt/frp/frpc.toml

start_service() {
  sleep 3
  procd_open_instance
  procd_set_param command $PROG -c $CONF_DIR
  procd_set_param user root
  procd_set_param limits core="unlimited"
  procd_set_param limits nofile="1000000 1000000"
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
  procd_close_instance
  echo "frpc is started!"
}

stop_service() {
  service_stop $PROG
  echo "frpc is stopped!"
}

reload_service() {
  stop
  echo "frpc is restarted!"
  start
}
